name: happyfoods
description: A new Flutter application. happy_foods 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0
  modal_progress_hud: ^0.1.3
  flutter_spinkit: "^4.0.0"
  http:
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.0
  sqflite: any
  connectivity: ^0.4.8+6
  intl: ^0.15.7
  provider: ^2.0.0+1
  path_provider: ^1.6.8
  share_extend: ^1.1.5
  flutter_rating_bar: ^1.1.0
  awesome_dialog:
  url_launcher: ^5.4.7
  image_picker: 0.5.0+3
  dio: ^3.0.9
  firebase_messaging: ^6.0.16
  fdottedline: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/happyfoodlogo.png"
  image_path_ios: "images/happyfoodlogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/doodle.jpg
    - images/bg.jpg
    - images/user.png
    - images/logo.jpg
    - images/food.png
    - images/pic.png
    - images/nodatafound.png
    - images/fresh.jpg
    - images/instagram.png
    - images/facebook.png
    - images/green.png
    - images/orange.png
    - images/red.png
    - images/payment.png
    - images/bag.png
    - images/happyfoodlogo.png
    - images/caltwo.png
    - images/Dashboard/attendance.png
    - images/Dashboard/explore_more.png
    - images/Dashboard/homework.png
    - images/Dashboard/kids_activity.png
    - images/Dashboard/skill_tag.png